### ISSUE TITLE
Multiplayer Backend

### ISSUE THREAD

**Issue by csmith1188** [csmith1188/pokepucks#24]
Goals:

- [x] Log in with formbar.
- [x] Create new game with a game code.
- [x] Get both players in a "chat room" that uses that game code.
- [x] Cleanup old games automatically or when ended by players.
- [x] Make sure PokePucks game works online between 2 players when merged with the chatroom.

**Comment by Brand24376** [comment]
Made a single user connect to the chatroom and be able to send and receive messages from and to the server with Issue #25.

**Comment by Brand24376** [comment]
Working on Issue #30 next for this Issue.

**Comment by Brand24376** [comment]
Computer hosting the server can have two windows open and each window can see the messages sent by each other.
Also upgraded the chatroom to use socket.io.

**Comment by Brand24376** [comment]
Added chat activity detection. Detects when user joins and disconnects allowing you to send custom messages when a user joins or disconnects from the chatroom either to only the user, everybody but the user, or everybody. Also detects when a user is typing and tells everyone else when that person is typing and if they stop typing before sending that message, after a set amount of seconds, the test saying that that person is typing will disappear. 
Pull request for this not made yet but I made this while working on Issue #30.

**Comment by Brand24376** [comment]
Finished Issue #30. Users connected to the same domain can join the server.

**Comment by Brand24376** [comment]
Finished Issue #36.

**Comment by Brand24376** [comment]
Working on Issue #41 this week for this issue. Might also do Issue #39 if I have enough time.

**Comment by Brand24376** [comment]
![chatroomPrototype](https://github.com/csmith1188/pokepucks/assets/82458664/7f0a0ba5-1bd8-477e-bd4c-abf465d0b2d5)

**Comment by Brand24376** [comment]
Working on issue #48 for this week. Should have wrote this at the beginning of the week.

**Comment by Brand24376** [comment]
Finished Issue #48. Going to keep this issue open until I'm done fixing a bug that will be put as an issue.

**Comment by Brand24376** [comment]
Im satisfied with where the multiplayer backend is at right now and I will now close it.
