### ISSUE TITLE
CSS for PokePucks Game

### ISSUE THREAD

**Issue by Brand24376** [csmith1188/pokepucks#49]
Make the CSS for the chatroom. Make it look like the picture here: 
![image](https://github.com/csmith1188/pokepucks/assets/82458664/39084117-3130-427e-b863-efb359962075)
Make sure that the colors are similar to the PokePucks color displayed in the PokePucks rule site.
Above is going to change now that the chatroom and game are combined. Idea will still be similar though.

**Comment by Anton255561** [comment]
will be adding bigger chatbox to be more visible
and will be adding different format on the multiple buttons being added
